### ISSUE TITLE
Compilation of jinx-mod.dll failed

### ISSUE THREAD

**Issue by doesn123** [minad/jinx#44] opened 2023-04-19 14:12 UTC
I'm getting this error when enabling the mode:

cc -I. -O2 -Wall -Wextra -fPIC -shared -o jinx-mod.dll jinx-mod.c -I/usr/include/enchant-2 -lenchant-2
Jinx: Compilation of jinx-mod.dll failed

I'm using Windows 11. I had to update exec-path with the following as the 'cc.exe' binary wasn't found:  
 (setq exec-path (cons "C:/msys64/ucrt64/bin" exec-path))

Thanks in advance!

**Comment by minad** [comment] 2023-04-19 14:36
Thanks for the report. 

Are there more error messages which could tell you what the problem is? The path `-I/usr/...` is obviously wrong on Windows for example. Did you make sure that libenchant and pkgconfig are available for compilation? You could also try to compile jinx-mod.dll manually and place it in the Jinx installation directory of your Emacs installation.

I close this issue since I don't have access to a Windows machine and I cannot be of help. If someone knowledgeable about Windows comes along I am happy to accept a patch which makes the installation on Windows smooth. There exist other Emacs packages which use dynamic modules like Vterm. Maybe they have solved how to do compilation on Windows correctly.

**Closed by minad** 2023-04-19 14:36 UTC

**Comment by doesn123** [comment] 2023-04-20 17:46
Thanks for your response. I'm not quite technically proficient enough to answer your questions unfortunately. I'll certainly give Jinx a try if I ever move back to Linux, thanks again!
